# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 300, 60))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushBtn_filter = QtWidgets.QPushButton(self.frame)
        self.pushBtn_filter.setGeometry(QtCore.QRect(0, 0, 60, 60))
        self.pushBtn_filter.setMaximumSize(QtCore.QSize(60, 60))
        self.pushBtn_filter.setObjectName("pushBtn_filter")
        self.pushBtn_eliminate = QtWidgets.QPushButton(self.frame)
        self.pushBtn_eliminate.setGeometry(QtCore.QRect(60, 0, 80, 60))
        self.pushBtn_eliminate.setMaximumSize(QtCore.QSize(80, 60))
        self.pushBtn_eliminate.setObjectName("pushBtn_eliminate")
        self.pushBtn_autoPlot = QtWidgets.QPushButton(self.frame)
        self.pushBtn_autoPlot.setGeometry(QtCore.QRect(220, 0, 80, 60))
        self.pushBtn_autoPlot.setMaximumSize(QtCore.QSize(80, 60))
        self.pushBtn_autoPlot.setObjectName("pushBtn_autoPlot")
        self.pushBtn_add = QtWidgets.QPushButton(self.frame)
        self.pushBtn_add.setGeometry(QtCore.QRect(140, 0, 80, 60))
        self.pushBtn_add.setMaximumSize(QtCore.QSize(80, 60))
        self.pushBtn_add.setObjectName("pushBtn_add")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 80, 981, 481))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_filter = QtWidgets.QWidget()
        self.page_filter.setObjectName("page_filter")
        self.label = QtWidgets.QLabel(self.page_filter)
        self.label.setGeometry(QtCore.QRect(130, 100, 101, 51))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_filter)
        self.page_eliminate = QtWidgets.QWidget()
        self.page_eliminate.setObjectName("page_eliminate")
        self.label_2 = QtWidgets.QLabel(self.page_eliminate)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 101, 81))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_eliminate)
        self.page_add = QtWidgets.QWidget()
        self.page_add.setObjectName("page_add")
        self.label_3 = QtWidgets.QLabel(self.page_add)
        self.label_3.setGeometry(QtCore.QRect(100, 100, 47, 13))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_add)
        self.page_autoPlot = QtWidgets.QWidget()
        self.page_autoPlot.setObjectName("page_autoPlot")
        self.label_4 = QtWidgets.QLabel(self.page_autoPlot)
        self.label_4.setGeometry(QtCore.QRect(90, 110, 47, 13))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_autoPlot)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuGraph = QtWidgets.QMenu(self.menubar)
        self.menuGraph.setObjectName("menuGraph")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionBoxPlot = QtWidgets.QAction(MainWindow)
        self.actionBoxPlot.setObjectName("actionBoxPlot")
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuGraph.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushBtn_filter.setText(_translate("MainWindow", "Filter"))
        self.pushBtn_eliminate.setText(_translate("MainWindow", "Elimination"))
        self.pushBtn_autoPlot.setText(_translate("MainWindow", "AutoPlot"))
        self.pushBtn_add.setText(_translate("MainWindow", "Addition"))
        self.label.setText(_translate("MainWindow", "Filter"))
        self.label_2.setText(_translate("MainWindow", "Elimination"))
        self.label_3.setText(_translate("MainWindow", "Addition"))
        self.label_4.setText(_translate("MainWindow", "autoPlot"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuGraph.setTitle(_translate("MainWindow", "Graph"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionBoxPlot.setText(_translate("MainWindow", "BoxPlot"))



